config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/login', to:"home#login"
  get 'home/login2'
  get 'home/Employee_page', to: 'home#Employee_page'
  get 'home/Employee_page2'
  get 'admin_page/search'
  get 'admin_page/search1'
  get '/newfloor', to: 'admin_page#newfloor'
  get '/newslot', to: 'admin_page#newslot'
  post '/createfloor', to: 'admin_page#createfloor'
  post '/createslot', to: 'admin_page#createslot'
  get '/assignfloor', to: 'admin_page#assignfloor'
  patch "/assign_floor", to: "admin_page#assign_floor"
  get '/delete_user', to: 'home#delete_user', as: :delete
  resources :admin_page do
    get '/delete', to: 'admin_page#delete'
  end
  resources :employee do
    get '/delete', to: 'employee#delete'
    get '/show1', to: 'employee#show1'
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  enum :user_type, [:employee, :admin], default: :employee
  has_many :floor
  scope :show, -> { where(:user_type => "employee")}
  scope :search, lambda {|query|where(["name LIKE?","%#{query}%"])}
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  def auth
    begin
      if session[:employee_id].blank? && session[:admin_id].blank?
        raise "what"
      end
    rescue
      redirect_to root_path
    end
  end
  def index
    auth
    unless session[:employee_id].blank?
      @employee = Employee.find(session[:employee_id])
      @floor = @employee.floor.first
      unless @floor.blank?
        @slot = @floor.slots.where(parking_status: "full")
      end
      
    end
  end
  def new
    auth
    @employee = Employee.find(session[:employee_id])
    @floor = @employee.floor.first
    @slot = @floor.slots.where(parking_status: "empty").first
    @vec = @slot.vechiles.new unless @slot.blank?
  end
  def create
    @employee = Employee.find(session[:employee_id])
    @floor = @employee.floor.first
    @slot = @floor.slots.where(parking_status: "empty").first
    @vec = @slot.vechiles.build(vehicles_params)
    if @vec.save
      @slot.update(parking_status: "full")
      redirect_to employee_index_path
    else
      render 'index'
    end
  end
  def show
    auth
    @employee = Employee.find(session[:employee_id])
    @floor = @employee.floor.first
    @slot = @floor.slots.first
    @vec = Vechile.find(params[:id])
  end
  def edit
    auth
    @employee = Employee.find(session[:employee_id])
    @floor = @employee.floor.first
    @slot = @floor.slots.first
    @vec = Vechile.find(params[:id])
    @vec.created_at = @vec.created_at.strftime("%Y-%m-%d %H:%M:%S")
    @vec.updated_at = Time.now.strftime("%Y-%m-%d %H:%M:%S")
  end
  def update
    @employee = Employee.find(session[:employee_id])
    @floor = @employee.floor.first
    @slot = @floor.slots.first
    @vec  = Vechile.find(params[:id])
    @vec.updated_at = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    if @vec.update(vehicles_params)
      @vec.price = (100 * total_time(@vec))
      @slot.update(parking_status: "empty")
      redirect_to employee_index_path(@vec)
    else
      render ('edit')
    end
  end

  def destroy
    auth
    @employee = Employee.find(session[:employee_id])
    @vec = Vechile.find(params[:id])
    @slot = Slot.find(@vec.slot_id)
    @slot.update(parking_status: "empty")
    @vec.destroy
    redirect_to employee_index_path
  end

  def show1
    auth
    @employee = Employee.find(params[:employee_id])
    @vec = Vechile.find_by(params[:q])
  end
  
  private
  def vehicles_params
    params.require(:vechile).permit(:number, :car_model_name, :created_at, :updated_at)
  end
  def vec
    @vec  = Vechile.find(params[:id])
  end
  def total_time(vec)
    check_date = vec.updated_at.strftime('%d').to_i - vec.created_at.strftime('%d').to_i
    #if data change so we calculate total hours and minutes
    if check_date > 0
        total_hours = 24 + vec.updated_at.strftime('%H').to_i - vec.created_at.strftime('%H').to_i
    else
        total_hours = vec.updated_at.strftime('%H').to_i - vec.created_at.strftime('%H').to_i
    end
    if total_hours > 0
        total_min = 60 + vec.updated_at.strftime('%M').to_i - vec.created_at.strftime('%M').to_i
    else
        total_min = vec.updated_at.strftime('%M').to_i - vec.created_at.strftime('%M').to_i
    end
    if check_date > 0
        if total_min > 0
            total_hours = total_hours + 1
        else
            total_hours
        end
    else
        if total_min > 0
            total_hours = total_hours + 1
        else
            total_hours
        end
    end
end
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employee/edit.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= link_to "Back to the Index Page", employee_index_path, class: "link1" %>
<br><br>
<div class="container">
		<br>
		<h1 class="h1_new">Parking Out</h1>

		<%=form_for @vec, url: employee_path(@vec), :method => 'patch' do |f| %>

		<label><b>Vehicle Number</b></label><br>

			<%= f.text_field :number %> <br><br>

			<label><b>Car Model Name</b></label><br>

			<%= f.text_field :car_model_name %> <br>
			<label><b>Parking In</b></label><br>
			<%= f.text_field :created_at%> <br>
			<label><b>Parking Out</b></label><br>
			<%= f.text_field :updated_at%> <br>

			<div class="form-button">	

				<%= f.submit "Parking Out the Vehicle",  :class => "button"%> 
				
		</div>

		<% end %>
		<br>
</div>

app/views/employee/index.html.erb
<% if !flash[:notice].blank?%>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<%end%>
<br>
<div class="col-lg-12">
	<h1 class="card-title text-center">Parking Management System</h1>
	<br>
	<%= link_to "Add new Vehicle", "employee/new", class:'action new', class: "link1"%>
	<h3 class="mt-4 mb-4 text-center">Vehicle List</h3>
	<% unless @slot.blank?%>
		<% @slot.each do |v|%>
		<div class="row">
			<div class="col-lg-4">
				<div class="card shadow mb-3 mt-3">
					<div class="card-body">
						<%unless v.vechiles.blank?%>
							<h4 class="card-title">Vehicle number : <%= v.vechiles.first.number%></h4>
							<h4 class="card-title">Vehicle Model : <%= v.vechiles.first.car_model_name%></h4>
							<%= link_to "Show", employee_path(v.vechiles.first.id), class:"btn btn-danger btn-lg" %>
							<%= link_to "Parking Out", edit_employee_path(v.vechiles.first.id), class:"btn btn-primary btn-lg" %>
							<%= link_to "Wrong Entry", employee_path(v.vechiles.first.id), class:"btn btn-danger btn-lg", data: {
								turbo_method: :delete,
								turbo_confirm: "Are you sure that the entry is wrong?"
							} %>
						<%end%>
					</div>
				</div>
			</div>
		</div>
		<% end%>
	<%end%>
</div>

app/views/employee/new.html.erb
<br>
<%= link_to "Back to the Index Page", employee_index_path, class: "link1" %> <br> <br>
<div class="container">
    <br>
  <%unless @vec.blank? %>
    <h1 class="h1_new">Add Car</h1>
    <%=form_for @vec, url: "/employee", method: :post do |f| %>
    <label><b>Vehicle Number</b></label><br>
      <%= f.text_field :number %> <br><br>
      <label><b>Model No.</b></label><br>
      <%= f.text_field :car_model_name %> <br>
    <br>
      <div class="form-button">
        <%= f.submit "Parking In",  :class => "button"%>
    </div>
    <br>
    <% end %>
  <% else%>
    <h3 class="text-center">All the Parking Slots are full</h3>
  <%end%>
</div>

app/views/employee/show.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= link_to "Back to the Index Page", employee_index_path, class: "link1" %>
<div class="subjects_show">
    <% if !flash[:notice].blank?%>
		<div class="notice">
			<%= flash[:notice]%>
		</div>
    <%end%>
    <table class="listing table_view">
        <tr>
                <tr>
                    <td><b>Functions</b></td>
                  <td><b><p>Show Subject</p></b></td>
                </tr>

                <tr>
                    <th>Name</th>
                    <td><%= @vec.number %></td>
                </tr>
                <tr>
                  <th>Model Name</th>
                  <td><%= @vec.car_model_name %></td>
                </tr>
                <tr>
                    <th>Parking in</th>
                    <td><%= @vec.created_at %></td>
                </tr>
                <tr>
                    <th>Parking Out</th>
                    <td><%= @vec.updated_at %></td>
                </tr>
        </tr>
    </table>
</div>

app/views/employee/show1.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= link_to "Back to the Index Page", admin_page_index_path, class: "link1" %>
<div class="subjects_show">

    <table class="listing table_view">
        <tr>  
                <tr>
                    <td><b>Functions</b></td>  
                  <td><b><p>Show Subject</p></b></td>
                </tr>

                <tr>
                    <th>Name</th>
                    <td><%= @vec.number %></td>
                </tr>
                <tr>
                  <th>Model Name</th>
                  <td><%= @vec.car_model_name %></td>
                </tr>
                <tr>
                    <th>Floor</th>
                    <td><%= @vec.slot.floor.number %></td>
                  </tr>
                <tr>
                    <tr>
                        <th>slot</th>
                        <td><%= @vec.slot.slot_number %></td>
                      </tr>
                    <tr>
                    <th>Parking in</th>
                    <td><%= @vec.created_at %></td>
                </tr>
                <tr>
                    <th>Parking Out</th>
                    <td><%= @vec.updated_at %></td>
                </tr>
        </tr>
        
        
    </table>
</div>