config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/login', to:"home#login"
  get 'home/login2'
  get 'home/Employee_page', to: 'home#Employee_page'
  get 'home/Employee_page2'
  get 'admin_page/search'
  get 'admin_page/search1'
  get '/newfloor', to: 'admin_page#newfloor'
  get '/newslot', to: 'admin_page#newslot'
  post '/createfloor', to: 'admin_page#createfloor'
  post '/createslot', to: 'admin_page#createslot'
  get '/assignfloor', to: 'admin_page#assignfloor'
  patch "/assign_floor", to: "admin_page#assign_floor"
  get '/delete_user', to: 'home#delete_user', as: :delete
  resources :admin_page do
    get '/delete', to: 'admin_page#delete'
  end
  resources :employee do
    get '/delete', to: 'employee#delete'
    get '/show1', to: 'employee#show1'
  end
end

app/controllers/admin_page_controller.rb
class AdminPageController < ApplicationController
  def auth
    begin
      if session[:employee_id].blank? && session[:admin_id].blank?
        raise "what"
      end
    rescue
      redirect_to root_path
    end
  end
  def index
    auth
    @emp = Employee.pluck(:user_type)
    @employee = Employee.show
  end
  def new
    auth
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      flash[:notice] = "Employee created successfully......"
      redirect_to admin_page_index_path
    else
      render('new')
    end
  end
  def show
    auth
    @employee = Employee.find(params[:id])
    @floor = @employee.floor.first
    unless @floor.blank?
      @f = Floor.find_by(employee_id: @employee.id)
      @slot = @floor.slots.where(parking_status: "full")
      @vec = @slot.count()
    else
      @vec = 0
    end
  end

  def edit
    auth
    @employee = Employee.find(params[:id])
  end
  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      flash[:notice] = "Employee details update successfully ....."
      redirect_to admin_page_path(@employee)
    else
      render ('edit')
    end
  end
  def delete
    auth
    @employee = Employee.find(params[:admin_page_id])
  end
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to admin_page_index_path
  end
  def search
    auth
  end
  def search1
    @vec = Vechile.search(params[:q])
    if @vec
      redirect_to employee_show1_path(@vec.ids)
    else
      render ('search')
    end
  end
  def newfloor
    auth
  end
  def createfloor
    @employee = Employee.find_by(email: params[:email])
    if params[:number].to_i > 0
      params[:number].to_i.times do |j|
          @floor = Floor.find_by(number: j+1)
          if @floor.blank?
            @floor = @employee.floor.new(number: j+1)
            if @floor.save
              10.times{
                |i|
                @slot = @floor.slots.create(slot_number: i+1)
              }
              flash[:notice] = "Successfully Assigned..."
              redirect_to admin_page_index_path
            else
              render('new')
            end
          end
      end
    else
        flash[:notice] = "Please put floor in positive number"
        render('newfloor')
    end
  end
  def newslot
    auth
  end
  def createslot
    @floor = Floor.find_by(number: params[:number])
    if params[:slot_number].to_i > 0
      if @floor.slots.create(slot_number: params[:slot_number]).valid?
        params[:slot_number].to_i.times{
          |i|
          @slot = @floor.slots.find_by(slot_number: i+1)
          if @slot.blank?
            @slot = @floor.slots.create(slot_number: i+1)
          end
        }
      else
        flash[:notice] = "You have already created all the slots"
        render('newslot')
      end
    else
      flash[:notice] = "Please enter the slot in postivie number"
      render ('newslot')
    end
  end

  def assignfloor
    auth
  end

  def assign_floor
    @employee = Employee.find_by(email: params[:email])
    @floor = Floor.find_by(number: params[:number])
    if @floor.update(employee_id: @employee.id)
      flash[:notice] = "Employee floor details update successfully ....."
      redirect_to admin_page_path(@employee)
    else
      render ('assignfloor')
    end
  end

  private
  def employee_params
    params.require(:employee).permit(:name, :email, :password, :user_type)
  end
end

app/helpers/admin_page_helper.rb
module AdminPageHelper
end

app/views/admin_page/assignfloor.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= link_to "Back to the Index Page", admin_page_index_path, class: "link1" %>
<br><br>
<div class="container">
		<br>
		<h1 class="h1_new">Update Employee Floor Details</h1>
		<%=form_with url: "/assign_floor", :method => 'patch' do |f| %>
			<label><b>Email ID</b></label><br>
			<%= f.email_field :email %> <br>
      <label><b>Floor</b></label><br>
			<%= f.number_field :number %> <br>
			<div class="form-button">
				<%= f.submit "Assign Floor",  :class => "button"%>
		</div>
		<% end %>
</div>

app/views/admin_page/delete.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= link_to "Back to the Index Page", admin_page_index_path, class: "link1" %>
<div class="subject_delete">
  <h1 class="text-center">Delete Employee</h1>
  <%=form_for @employee, url: admin_page_path(@employee), :method => 'delete' do |f| %>
    <p><%= flash.alert = "Are you sure you want to fire \"#{@employee.name}\"?"%></p>
    <div class="form-button">
      <%= f.submit "Fired Employee",  :class => "button"%> 
    </div>
  <% end %>
</div>

app/views/admin_page/edit.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= link_to "Back to the Index Page", admin_page_index_path, class: "link1" %>
<br><br>
<div class="container">
		<br>
		<h1 class="h1_new">Update Employee Details</h1>

		<%=form_for @employee, url: admin_page_path(@employee), :method => 'patch' do |f| %>

		<label><b>Name</b></label><br>

			<%= f.text_field :name %> <br><br>

			<label><b>Email ID</b></label><br>

			<%= f.email_field :email %> <br>

      <label><b>Password</b></label><br>

			<%= f.password_field :password %> <br>

			<div class="form-button">	

				<%= f.submit "Update Subject",  :class => "button"%> 
				
		</div>

		<% end %>
</div>

app/views/admin_page/index.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<% if !flash[:notice].blank?%>
		<div class="notice">
			<%= flash[:notice]%>
		</div>
<%end%>
<div class="col-lg-12">
	<h1 class="card-title text-center">Parking Management System</h1>
	<br>
	<%= link_to "Add Floor", "/newfloor", class: "link" %>
	<%= link_to "Add Slot", "/newslot", class: "link" %>
	<%= link_to "Assign Floor", "/assignfloor", class: "link" %>
	<%= link_to "Add new Employee / User", "admin_page/new", class: "link1" %>
	<%= link_to "Search the Vehicle", "admin_page/search", class: "link1 link2" %>
	<h3 class="mt-4 mb-4 text-center">Employees List</h3>
	<% if @emp.include? ("employee") %>
		<% @employee.each do |emp|%>
			<div class="row">
				<div class="col-lg-4">
					<div class="card shadow mb-3 mt-3">
						<div class="card-body">
								<h4 class="card-title"><%=emp.name.camelize %></h4>
								<%= link_to "Cars", admin_page_path(emp.id), class:"btn btn-danger btn-lg"%>
								<%= link_to "Update Employee", edit_admin_page_path(id: emp.id), class:"btn btn-primary btn-lg"%>
								<%= link_to "Fired", admin_page_delete_path(emp.id), class:"btn btn-danger btn-lg"%>
						</div>
					</div>
				</div>
			</div>
		<%end%>
	<% else%>
		<h2 class="text-center">There are no employee present in your organization</h2>
	<%end%>
</div>

app/views/admin_page/new.html.erb
<%= link_to "Back to the Index Page", admin_page_index_path, class:"link1" %>
<br><br>
<div class="container">
  <br>
  <h1 class="h1_new">Create Employee/User</h1>

  <%=form_for @employee, url: "/admin_page", method: :post do |f| %>


  <label><b>Name</b></label><br>

    <%= f.text_field :name, required: true  %> <br><br>

    <label><b>Email</b></label><br>

    <%= f.email_field :email, required: true  %> <br>

    <label><b>Password</b></label><br>

    <%= f.password_field :password, required: true %> <br>

    <label><b>Type</b></label><br>
    <%= f.text_field :user_type %> <br>
    <br>
    <div class="form-button">	

      <%= f.submit "Create Employee",  :class => "button"%>
  </div>
  <br>

  <% end %>
</div>

app/views/admin_page/newfloor.html.erb
<%= link_to "Back to the Index Page", admin_page_index_path, class:"link1" %>
<% if !flash[:notice].blank?%>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= flash[:notice]%>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<%end%>
<br><br>
<div class="container">
  <br>
  <h1 class="h1_new">Create Floor</h1>

  <%=form_with url: "/createfloor", method: :post do |f| %>
    <label><b>Employee Email</b></label>
    <%= f.email_field :email, required: true %> <br>
    <label><b>Number of Floor</b></label><br>
    <%= f.number_field :number, required: true %> <br>
    <br>
    <div class="form-button">
      <%= f.submit "Add Floor",  :class => "button"%>
  </div>
  <br>
  <% end %>
</div>

app/views/admin_page/newslot.html.erb
<%= link_to "Back to the Index Page", admin_page_index_path, class:"link1" %>
<% if !flash[:notice].blank?%>
		<div class="notice">
			<%= flash[:notice]%>
		</div>
<%end%>
<br><br>
<div class="container">
  <br>
  <h1 class="h1_new">Create Slot</h1>

  <%=form_with url: "/createslot", method: :post do |f| %>


  <label><b>Floor Number</b></label><br>

    <%= f.number_field :number, required: true  %> <br><br>

    <label><b>Number of Slot</b></label><br>

    <%= f.number_field :slot_number, required: true  %> <br>
    <br>
    <div class="form-button">

      <%= f.submit "Add Slot",  :class => "button"%>
  </div>
  <br>

  <% end %>
</div>

app/views/admin_page/search.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= link_to "Back to the Index Page", admin_page_index_path, class:"link1" %>
<div class="container">
  <%= form_tag(admin_page_search1_path, :method => "get") do %>
    <%= label_tag(:q, "Number:") %> <br>
    <%= text_field_tag(:q) %> <br><br>
    <div class="form-button">
      <%= submit_tag("Search") %>
    </div>
    <br>
  <% end %>
</div>

app/views/admin_page/show.html.erb
<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<% if !flash[:notice].blank?%>
<div class="notice">
  <%= flash[:notice]%>
</div>
<%end%>
<div class="col-lg-5 mt-5">
  <div class="card shadow mb-3">
    <div class="card-body">
      <h4 class="card-title"><%= @employee.name.camelize %></h4>
      <div class="row mt-3">
        <div class="col-lg-7">
          <h4>Email: <span class="badge bg-primary"><%= @employee.email %></span></h4>
        </div>
        <div class="col-lg-5 mt-3">
          <h4>Assign Floor: <span class="badge bg-primary">
            <%if @f.blank? %>
              0
            <% else%>
              <%= @f.number %>
            <%end%>
          </span></h4>
          <h4>Cars: <span class="badge bg-primary"><%= @vec%></span></h4>
        </div>
      </div>
      <%= link_to "Back to the Index Page", admin_page_index_path, class: "btn btn-outline-danger btn-lg mt-3" %>
    </div>
  </div>
</div>