config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/login', to:"home#login"
  get 'home/login2'
  get 'home/Employee_page', to: 'home#Employee_page'
  get 'home/Employee_page2'
  get 'admin_page/search'
  get 'admin_page/search1'
  get '/newfloor', to: 'admin_page#newfloor'
  get '/newslot', to: 'admin_page#newslot'
  post '/createfloor', to: 'admin_page#createfloor'
  post '/createslot', to: 'admin_page#createslot'
  get '/assignfloor', to: 'admin_page#assignfloor'
  patch "/assign_floor", to: "admin_page#assign_floor"
  get '/delete_user', to: 'home#delete_user', as: :delete
  resources :admin_page do
    get '/delete', to: 'admin_page#delete'
  end
  resources :employee do
    get '/delete', to: 'employee#delete'
    get '/show1', to: 'employee#show1'
  end
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Parking System</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active aria-current page" %>
        </li>
      </ul> 
      <ul class="navbar-nav">
        <li class="nav-item">
          <% unless session[:admin_id].blank? && session[:employee_id].blank? %>
              <%= link_to "Log Out", delete_path, class: "nav-link active aria-current page"%>
          <% end%>
        </li>
      </ul>
    </div>
  </div>
</nav>