config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/login', to:"home#login"
  get 'home/login2'
  get 'home/Employee_page', to: 'home#Employee_page'
  get 'home/Employee_page2'
  get 'admin_page/search'
  get 'admin_page/search1'
  get '/newfloor', to: 'admin_page#newfloor'
  get '/newslot', to: 'admin_page#newslot'
  post '/createfloor', to: 'admin_page#createfloor'
  post '/createslot', to: 'admin_page#createslot'
  get '/assignfloor', to: 'admin_page#assignfloor'
  patch "/assign_floor", to: "admin_page#assign_floor"
  get '/delete_user', to: 'home#delete_user', as: :delete
  resources :admin_page do
    get '/delete', to: 'admin_page#delete'
  end
  resources :employee do
    get '/delete', to: 'employee#delete'
    get '/show1', to: 'employee#show1'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless session[:admin_id].blank?
      redirect_to admin_page_index_path
     end
     unless session[:employee_id].blank?
      redirect_to employee_index_path
     end
  end
  def login
  end
  def login2
    @employee = Employee.find_by(email: params[:email], password: params[:password])
    if @employee
     if @employee.user_type.upcase == "ADMIN"
       session[:admin_id]=@employee.id
       unless session[:admin_id].blank?
        redirect_to admin_page_index_path
       end
     elsif @employee.user_type.upcase == "EMPLOYEE"
       session[:employee_id] = @employee.id
       unless session[:employee_id].blank?
        redirect_to employee_index_path
       end
     else
       render 'index'
     end
    else
      render 'index'
    end
  end
  def delete_user
    session.delete(:admin_id)
    session.delete(:employee_id)
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/delete_user.html.erb
<h1>Log Out</h1>

app/views/home/index.html.erb
<div class="index">
    <h1 class="text-center index_home">Welcome to ABC Parking</h1> 
    <p class="text-center p_home">Click here to Login</p>
    <div class="login">
      <h3><%= link_to "Login", home_login_path, class: "link" %></h3>
    </div>
    
    <h1 class="text-center index_home">24/7 Available Parking</h1> 
</div>

app/views/home/login.html.erb
<br><br>
<div class="col-lg-6 mx-lg-auto">
    <div class="card shadow">
      <div class="card-header">
        <h2 class="card-title text-center">Log In</h2>
      </div>
      <div class="card-body">
        <%= form_with url: home_login2_path, method: :get do |f| %>
          <div class="form-group">
            <%= f.label :email, class: "mb-2"%>
            <%= f.email_field :email, class: "form-control form-control-lg"%>
          </div>
          <div class="form-group">
            <%= f.label :password, class: "mb-2"%>
            <%= f.password_field :password, class: "form-control form-control-lg"%>
          </div>
          <div class="actions">
            <%= f.submit "Submit", class:"button btn"%>
          </div>
        <%end%> 
      </div>
    </div>
</div>